import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, CheckCircle2, ShieldCheck, Zap, WalletCards, Coins } from 'lucide-react';
import { PlatformIcon } from '../components/PlatformIcon';

const platforms=['Facebook','Instagram','TikTok','YouTube','X','Telegram'];
const services=[
 ['Facebook Page Followers','2,400 coins / 1k'],['Facebook Likes','1,600 coins / 1k'],['Facebook Post Comments','2,000 coins / 1k'],
 ['Instagram Followers','3,000 coins / 1k'],['Instagram Likes','1,600 coins / 1k'],['TikTok Followers','3,600 coins / 1k'],
 ['TikTok Video Views','700 coins / 1k'],['YouTube Views','5,000 coins / 1k'],['YouTube Subscribers','10,000 coins / 1k'],['X Followers','3,600 coins / 1k'],['Telegram Members','4,400 coins / 1k']
];

export const LandingPage:React.FC=()=> <div className="min-h-screen bg-[#090305] text-white">
<header className="border-b border-white/10 bg-[#0d0508]/80 backdrop-blur-xl pt-safe"><div className="max-w-6xl mx-auto h-16 px-4 flex items-center justify-between"><Link to="/" className="flex items-center gap-2.5"><div className="jb-logo"><span>JB</span></div><div className="font-black text-lg">JB Boster</div></Link><div className="text-[10px] sm:text-xs uppercase tracking-[.2em] font-black text-[#df6f8e] text-right">Social Growth</div></div></header>
<section className="max-w-6xl mx-auto px-4 sm:px-6 pt-12 pb-14"><div className="grid lg:grid-cols-[1.1fr_.9fr] gap-8 items-center"><div><div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-[#7d1738]/15 border border-[#a72b50]/30 text-[#e47b99] text-[10px] font-black uppercase tracking-wider"><Zap className="w-3.5 h-3.5"/> Social Media Growth Platform</div><h1 className="text-4xl sm:text-6xl font-black leading-[1.02] mt-5">Boost your <span className="text-[#df6f8e]">social presence.</span></h1><p className="text-slate-300 mt-5 max-w-xl leading-relaxed">JB Boster is a social-media boosting platform for creators, businesses and brands. Choose a platform, select followers, likes, views, comments or other available services, set your quantity and pay with coins.</p><div className="flex flex-col sm:flex-row gap-3 mt-7"><Link to="/register" className="jb-primary justify-center">Get Started <ArrowRight className="w-4 h-4"/></Link><Link to="/login" className="jb-secondary justify-center">Sign In</Link></div><div className="grid grid-cols-3 sm:grid-cols-6 gap-2 mt-7">{platforms.map(p=><div key={p} className="rounded-xl border border-white/10 bg-white/[.03] p-2.5 flex flex-col items-center gap-1.5"><PlatformIcon platform={p} className="w-5 h-5 text-[#df6f8e]"/><span className="text-[9px] font-black">{p}</span></div>)}</div></div><div className="jb-hero rounded-[28px] p-5 sm:p-6"><div className="text-xs font-black text-[#ef9ab1]">JB BOSTER COINS</div><div className="text-2xl font-black mt-2">1,000 coins = ₦500</div><p className="text-xs text-slate-400 mt-2">Buy coins securely through KoraPay and use them for your social-media orders.</p><div className="space-y-3 mt-5">{[['Choose a platform','Facebook, Instagram, TikTok, YouTube, X and Telegram.'],['Pick a service','Followers, likes, views, comments, members and more.'],['Set your quantity','The app calculates your coin cost before you place the order.'],['Track your orders','See your order status from one mobile-first dashboard.']].map(([a,b])=><div key={a} className="p-3.5 rounded-2xl bg-black/20 border border-white/10 flex gap-3"><CheckCircle2 className="w-5 h-5 text-[#df6f8e] shrink-0"/><div><div className="font-black text-sm">{a}</div><div className="text-xs text-slate-400 mt-1">{b}</div></div></div>)}</div></div></div></section>
<section className="max-w-6xl mx-auto px-4 sm:px-6 py-12"><div className="text-center mb-7"><h2 className="text-2xl sm:text-3xl font-black">Services & starting prices</h2><p className="text-xs text-slate-400 mt-2">Prices are shown in JB Boster coins. Exact cost depends on the quantity you choose.</p></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{services.map(([a,b])=><div className="jb-card p-4" key={a}><div className="text-xs font-black">{a}</div><div className="text-[11px] text-[#df6f8e] font-black mt-2">{b}</div></div>)}</div></section>
<section className="border-y border-white/10 bg-[#0d0508]"><div className="max-w-6xl mx-auto px-4 sm:px-6 py-12 grid md:grid-cols-3 gap-4">{[[ShieldCheck,'Secure KoraPay Funding','Buy coins through the real hosted KoraPay checkout.'],[Coins,'Simple Coin Pricing','1,000 coins equals ₦500, with your order cost calculated automatically.'],[WalletCards,'One Growth Dashboard','Manage your balance, orders, history and profile in one place.']].map(([I,a,b]:any)=><div className="jb-card p-5" key={a}><I className="w-7 h-7 text-[#df6f8e]"/><h3 className="font-black mt-4">{a}</h3><p className="text-xs text-slate-400 mt-2 leading-relaxed">{b}</p></div>)}</div></section>
<footer className="max-w-6xl mx-auto px-4 py-9 text-xs text-slate-500 flex justify-between gap-4"><span>© {new Date().getFullYear()} JB Boster</span><div className="flex gap-4"><Link to="/login">Login</Link><Link to="/register">Register</Link></div></footer>
</div>;
