import React from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight, CheckCircle2, Instagram, Facebook, Youtube, Music2, ShieldCheck, Zap, WalletCards} from 'lucide-react';
export const LandingPage:React.FC=()=> <div className="min-h-screen bg-[#090305] text-white">
<header className="border-b border-white/10 bg-[#0d0508]/75 backdrop-blur-xl pt-safe"><div className="max-w-6xl mx-auto h-16 px-4 flex items-center justify-between"><Link to="/" className="flex items-center gap-2.5"><div className="jb-logo"><span>JB</span></div><div className="font-black">JB BOOST<div className="text-[9px] text-[#df6f8e] tracking-[.2em]">SOCIAL GROWTH</div></div></Link><div className="flex gap-2"><Link to="/login" className="jb-secondary">Login</Link><Link to="/register" className="jb-primary">Get Started</Link></div></div></header>
<section className="max-w-6xl mx-auto px-4 sm:px-6 pt-14 pb-16"><div className="grid lg:grid-cols-[1.15fr_.85fr] gap-10 items-center"><div><div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-[#7d1738]/15 border border-[#a72b50]/30 text-[#e47b99] text-[10px] font-black uppercase tracking-wider"><Zap className="w-3.5 h-3.5"/> Social Media Growth Platform</div><h1 className="text-4xl sm:text-6xl font-black leading-[1.02] mt-5">Build a stronger <span className="text-[#df6f8e]">social presence.</span></h1><p className="text-slate-300 mt-5 max-w-xl leading-relaxed">JB BOOST gives creators, brands and businesses one simple place to order social-media growth services, fund their account securely and manage orders.</p><div className="flex flex-col sm:flex-row gap-3 mt-7"><Link to="/register" className="jb-primary justify-center">Create Free Account <ArrowRight className="w-4 h-4"/></Link><Link to="/login" className="jb-secondary justify-center">Sign In</Link></div><div className="flex flex-wrap gap-2 mt-7">{[['Facebook',Facebook],['Instagram',Instagram],['TikTok',Music2],['YouTube',Youtube]].map(([n,I]:any)=><span key={n} className="px-3 py-2 rounded-xl border border-white/10 bg-white/[.03] text-xs font-bold flex items-center gap-2"><I className="w-4 h-4 text-[#df6f8e]"/>{n}</span>)}</div></div><div className="jb-hero rounded-[30px] p-5 sm:p-7"><div className="text-xs font-black text-[#ef9ab1]">JB BOOST</div><div className="text-2xl font-black mt-2">Everything your growth workflow needs.</div><div className="space-y-3 mt-6">{[['Transparent service pricing','See minimums, maximums and unit pricing before ordering.'],['Secure wallet funding','Buy coins through the real KoraPay hosted checkout.'],['Order tracking','Keep your social-media orders and statuses in one place.'],['Mobile-first experience','Fast, compact and designed for phones.']].map(([a,b])=><div key={a} className="p-4 rounded-2xl bg-black/20 border border-white/10"><div className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-[#df6f8e] shrink-0"/><div><div className="font-black text-sm">{a}</div><div className="text-xs text-slate-400 mt-1">{b}</div></div></div></div>)}</div></div></div></section>
<section className="max-w-6xl mx-auto px-4 sm:px-6 py-14"><div className="text-center mb-8"><h2 className="text-2xl sm:text-3xl font-black">Popular services & starting prices</h2><p className="text-xs text-slate-400 mt-2">Final prices and quantity limits are shown before every order.</p></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['Instagram Followers','₦1,500 / 1k'],['Instagram Likes','₦800 / 1k'],['TikTok Views','₦350 / 1k'],['YouTube Views','₦2,500 / 1k'],['Facebook Followers','₦1,200 / 1k'],['TikTok Followers','₦1,800 / 1k'],['YouTube Subscribers','₦5,000 / 1k'],['Telegram Members','₦2,200 / 1k']].map(([a,b])=><div className="jb-card p-4" key={a}><div className="text-xs font-black">{a}</div><div className="text-[11px] text-[#df6f8e] font-black mt-2">{b}</div></div>)}</div></section>
<section className="border-y border-white/10 bg-[#0d0508]"><div className="max-w-6xl mx-auto px-4 sm:px-6 py-14"><div className="grid md:grid-cols-3 gap-4">{[[ShieldCheck,'Secure Payments','KoraPay checkout and server-side payment verification.'],[WalletCards,'Wallet & Coins','Fund your balance and use it to place orders.'],[Zap,'Fast Ordering','Simple service selection and order submission.']].map(([I,a,b]:any)=><div className="jb-card p-6" key={a}><I className="w-7 h-7 text-[#df6f8e]"/><h3 className="font-black mt-4">{a}</h3><p className="text-xs text-slate-400 mt-2 leading-relaxed">{b}</p></div>)}</div></div></section>
<footer className="max-w-6xl mx-auto px-4 py-10 text-xs text-slate-500 flex justify-between gap-4"><span>© {new Date().getFullYear()} JB BOOST</span><div className="flex gap-4"><Link to="/login">Login</Link><Link to="/register">Register</Link></div></footer>
</div>
